### ISSUE TITLE
Give a more precise error message when the type generation fails

### ISSUE THREAD

**Issue by kbrabrand** [vaffel/sql-to-graphql#24]
When trying to generate the GraphQL schema from a random database I'm getting an error from some part of the ast transformation.

```js
$ sql2graphql print --db vglive --password root

/home/kribrabr/development/sql-to-graphql/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
AssertionError: [{kind: init, key: [object Object], value: [object Object], loc: null, type: Property, comments: null, method: false, shorthand: false, computed: false, decorators: null}, {kind: init, key: [object Object], value: [object Object], loc: null, type: Property, comments: null, method: false, shorthand: false, computed: false, decorators: null}, {kind: init, key: [object Object], value: [object Object], loc: null, type: Property, comments: null, method: false, shorthand: false, computed: false, decorators: null}, false] does not match field "properties": [Property | SpreadProperty] of type ObjectExpression
    at add (/home/kribrabr/development/sql-to-graphql/node_modules/ast-types/lib/types.js:544:28)
    at /home/kribrabr/development/sql-to-graphql/node_modules/ast-types/lib/types.js:558:17
    at Array.forEach (native)
    at Object.defineProperty.value [as objectExpression] (/home/kribrabr/development/sql-to-graphql/node_modules/ast-types/lib/types.js:557:30)
    at generateType (/home/kribrabr/development/sql-to-graphql/steps/generate-types.js:57:33)
    at Object.generateTypes (/home/kribrabr/development/sql-to-graphql/steps/generate-types.js:22:27)
    at onTableDataCollected (/home/kribrabr/development/sql-to-graphql/cli.js:100:24)
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:691:13
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:52:16
    at done (/home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:243:21)
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:44:16
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:688:17
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:167:37
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:691:13
    at /home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:52:16
    at done (/home/kribrabr/development/sql-to-graphql/node_modules/async/lib/async.js:243:21)
```

**Comment by kbrabrand** [comment]
It would be nice getting this one out of the way as debugging the AST stuff is a pretty big hurdle for someone who's new to all of it. I'll see if I can figure something out here.

**Comment by rexxars** [comment]
Yeah, those errors are really hard to grasp. Unfortunately it's not easy to really make them much more user friendly. The problem is on our side, though. We're just not handling some specific case. For this database I should be able to reproduce it, but in general I'd need a db structure dump to reproduce and fix. 

If you haven't figured it out already, I had have a look tomorrow. Have only tested on a few different database setups so far, so I'm sure there is a lot of kinks and quirks to work out.

**Comment by rexxars** [comment]
Fixed this specific error, at least.
